### ISSUE TITLE
Name und Logo -> LamiFAZ

### ISSUE THREAD

**Issue by kdcdde** [kingschnulli/diel#14]
s.o.

**Comment by kingschnulli** [comment]
Logo bitte hier mit hinterlegen

**Comment by kdcdde** [comment]
Logo Files: 
https://drive.google.com/open?id=15SK-np87yDPeqtYkIL90DIiWk0jONUuJ&authuser=rskdmail%40gmail.com&usp=drive_fs

**Comment by kingschnulli** [comment]
[drive-download-20220928T084753Z-001.zip](https://github.com/kingschnulli/diel/files/9663174/drive-download-20220928T084753Z-001.zip)

**Comment by kdcdde** [comment]
fehlt noch bei der Login page "/login", und oben links in der Menübar ( /  )

**Comment by kingschnulli** [comment]
erledigt
