### ISSUE TITLE
BUG: Suche bei "Interessen" geht nicht

### ISSUE THREAD

**Issue by kdcdde** [kingschnulli/diel#18]
bekomme die Fehlermeldung "**APP_DEBUG is set to true while APP_ENV is not local**" wenn ich bei der Suchleiste in Interessen was eingebe.

![2022-12-15 09_22_33-Window](https://user-images.githubusercontent.com/85335871/207809184-f7072e7b-1595-4ff1-b1db-f7089cbd1297.png)

**Comment by kingschnulli** [comment]
erledigt
