### ISSUE TITLE
beim Abspeichern des Profils kommt ein Array Fehler

### ISSUE THREAD

**Issue by kdcdde** [kingschnulli/diel#2]
APP_DEBUG is set to true while APP_ENV is not local

This could make your application vulnerable to remote execution. [Read more about Ignition security.](https://flareapp.io/docs/ignition-for-laravel/security)[](http://flareapp.io/docs/ignition-for-laravel/introduction)

/usr/www/users/agdcgo/diel/
ErrorException
Undefined array key "interests"
https://diel.aggrod.de/user/profile-information

**Comment by kingschnulli** [comment]
erledigt
