### ISSUE TITLE
ADMIN: Familien-Report: mehr Filter- & Sortiermöglichkeiten benötigt

### ISSUE THREAD

**Issue by kdcdde** [kingschnulli/diel#24]
- Zeitlicher Filter sollte variabel sein. Z.B. Monat, Quartal, Jahr, Kita-Jahr (Sep-Aug); Filter Startdatum / Filter Enddatum
- Filter. z.B. nur nach "überfällig/rot" hilfreich
- Sortiermöglichkeiten nach Spalten fehlen: z.B. nach Name sortieren, oder nach Status(Ampel)

**Comment by doerne** [comment]
"Stunde Jahr Plan" & "Stunden Jahr Ist" weglassen 
Neue Spalte "Delta" Anzeige "Plan - IST"
