### ISSUE TITLE
Reports für Leitung

### ISSUE THREAD

**Issue by kingschnulli** [kingschnulli/diel#5]
Das müssten wir mal genau spezifizieren, welche Reports also Kennzahlen brauchen wir da.

**Comment by kdcdde** [comment]
bespreche ich mit Manuel und gebe eine Vorgabe ab.

**Comment by kdcdde** [comment]
![elternengagement](https://user-images.githubusercontent.com/85335871/192734922-34db5e82-69f3-413e-aa3b-e15e76e2659d.png) Excel sieht aktuell so aus... bekommen wir so eine Aufstellung hin?

**Comment by kdcdde** [comment]
kann der Report evtl. auch in Edit-Ansicht umgeschaltet werden? Zur manuellen Pflege durch Manuel? Bzw. gibts was Excel Ähnliches? Er ist das halt gewöhnt... ansonsten was, das ähnlich einfach für ihn funktioniert...

**Comment by kdcdde** [comment]
Wunsch v. Manuel: so viel wie möglich auf einer Seite darstellen (Excel ähnliche Liste mit allen Kindern bzw. Familien)

Frage, ob Einfärbung möglich ist (rot, orange, grün je nach geleisteten Stunden ->

  25% drunter rot
  50% und mehr orange
  Über 90% grün

Einzelansicht pro Familie (welche Events vergangen, welche kommen – evtl. Verwaltbarkeit?)

Manuel muss Stunden manuell bearbeiten können


abgestimmt mit Manuel (RK, 22.4.22)

**Comment by doerne** [comment]
![image](https://user-images.githubusercontent.com/22037797/193894484-011c5210-5698-4141-81dc-6eff0e1fb97e.png)

Hier ein Vorschlag um in deinem Framework zu bleiben

Suche: Direkt  nach einer Familie suchen
Filtern: nach Gruppen & Grippe / Kindergarten
Rating: Siehe Vorschlag mit Prozent Aufteilung

**Comment by doerne** [comment]
![image](https://user-images.githubusercontent.com/22037797/193896798-9a46de1d-9380-44d7-bd3b-6aa9a39ab6b1.png)

**Comment by doerne** [comment]
![LamiFAZ](https://user-images.githubusercontent.com/22037797/194826919-ecf68331-3eba-41ed-ab52-bd1c66381744.jpg)

Manuel wollte die aktuelle Stunden Auswertung auf das Jahr bezogen und auf den aktuelle Monat

Die Ampel bezieht sich auf den aktuellen Monat (Monat * Anzahl Kinder * 2)

**Comment by kingschnulli** [comment]
![image](https://user-images.githubusercontent.com/673805/206913827-8d6f81e8-c1f8-42b2-8a66-d0a56e89a31f.png)
